export const COPY = {
  es: {
    nav: { inicio: 'inicio', sobre: 'sobre', obra: 'obra', stack: 'stack', contacto: 'contacto' },
    loader: {
      step1: 'encendiendo la vela…',
      step2: 'colgando papeles picados…',
      step3: 'preparando la ofrenda…',
      ready: 'bienvenido',
    },
    hero: {
      greeting: '// hola, soy',
      name: 'Damian Tapia',
      role: 'full-stack developer · CDMX',
      tagline: 'Construyo código',
      taglineHl: 'que sobrevive al que lo escribe.',
      bio: 'Entre la vida y el bug. Dos años levantando altares de código para startups y marcas que quieren ser recordadas.',
      cta1: 'ver obra()',
      cta2: 'contacto.md',
      scroll: 'baja · scroll',
    },
    about: {
      label: 'sobre mí',
      title: 'Aquí yace el dev',
      subtitle: 'una ofrenda breve',
      body: [
        'Me llamo Damian Tapia y llevo dos años construyendo aplicaciones web que la gente no quiere cerrar. Trabajo con React, TypeScript y Node, pero me muevo cómodo en cualquier parte del stack.',
        'Creo que el buen software —como una buena ofrenda— se construye con intención: cada decisión, cada pixel, cada función cumple un propósito.',
        'Cuando no estoy codeando estoy buscando una nueva manera de prepararme un café.',
      ],
      meta: [
        { k: 'ubicación', v: 'CDMX, México' },
        { k: 'experiencia', v: '2 años' },
        { k: 'estado', v: '● disponible', live: true },
        { k: 'idiomas', v: 'ES nativo · EN B2' },
      ],
    },
    projects: {
      label: 'obra completa',
      title: 'La lotería de proyectos',
      subtitle: 'cuatro cartas · cuatro historias',
      featured: 'destacado',
      viewAll: 'ver todas las cartas →',
      cards: [
        { num: '01', slug: 'proline', name: 'Proline', tag: 'Frontend Dev & UI/UX', year: '2025–hoy', stack: ['Next.js','TypeScript','SCSS/BEM','Storybook','Prisma'], blurb: 'Lideré 15+ wireframes y prototipos en Figma para 7+ módulos críticos. Construí librería de 40+ componentes reutilizables con clean architecture, mobile-first y atomic design. Integré Storybook, diseñé esquemas Prisma e implementé endpoints de API.', icon: '🧱', featured: true, meta: '−18 hrs dev / sprint' },
        { num: '02', slug: 'xcamp', name: 'Xcamp', tag: 'Frontend Angular & UI/UX', year: '2025', stack: ['Angular 17','TypeScript','SCSS/BEM','Figma'], blurb: 'Optimicé 30+ componentes y creé ~15 nuevos en Angular 17 alineados al design system. Lideré migración responsiva móvil y tablet para flujos multi-paso. Definí 8+ flujos end-to-end en Figma.', icon: '🎯', meta: '−40% duplicación' },
        { num: '03', slug: 'clinica-pos', name: 'Clínica POS', tag: 'Fullstack freelance', year: '2023–2024', stack: ['MongoDB','Express','React','Node','JWT'], blurb: 'App fullstack en producción para clínica de medicina funcional: expedientes, POS, inventario y cobros con pagos parciales. CRUD para 200+ pacientes con roles, reportes PDF y escaneo de códigos de barras. Módulo POS con 50+ SKUs.', icon: '🏥', meta: 'sync tickets <100ms' },
        { num: '04', slug: 'co-labora', name: 'Co‑Labora', tag: 'Plataforma coworking', year: '2023–2024', stack: ['Next.js','TypeScript','Tailwind','MongoDB','AWS S3','Stripe'], blurb: 'Plataforma fullstack de descubrimiento y renta de espacios de coworking, de Figma a producción. Integración de Google Maps, Stripe para pagos y SendGrid para notificaciones. Gestión de imágenes con AWS S3 + Sharp.', icon: '🏢', meta: 'end-to-end funcional' },
      ],
    },
    stack: {
      label: 'caja de herramientas',
      title: 'El altar técnico',
      subtitle: 'siete veladoras encendidas',
      hint: 'hover · prende la vela',
      cats: [
        { t: 'frontend', items: ['Angular 17+', 'React 18', 'Next.js 13+', 'TypeScript', 'JavaScript ES6+'] },
        { t: 'styling', items: ['Tailwind CSS', 'SCSS/SASS', 'DaisyUI', 'CSS-in-JS', 'BEM'] },
        { t: 'backend', items: ['Node.js', 'Express', 'PostgreSQL'] },
        { t: 'database', items: ['MongoDB', 'Prisma ORM'] },
        { t: 'tools', items: ['Git', 'Figma', 'Storybook', 'Jira', 'Postman', 'ClickUp', 'Asana', 'PostHog', 'GrowthBook'] },
        { t: 'ui/ux', items: ['Design Systems', 'Responsive Design', 'Mobile-First', 'Atomic Design', 'User Flow Optimization'] },
        { t: 'apis', items: ['REST APIs', 'Stripe API', 'Google Maps API'] },
      ],
    },
    contact: {
      label: 'ofrenda',
      title: 'Dejemos una ofrenda en tu proyecto.',
      subtitle: 'cuéntame qué quieres construir',
      emailBtn: 'copiar correo',
      copied: '✓ copiado',
      or: 'o búscame en',
      footer: 'hecho con ♥ y café de olla · que descansen en paz los bugs · ',
    },
  },
  en: {
    nav: { inicio: 'home', sobre: 'about', obra: 'works', stack: 'stack', contacto: 'contact' },
    loader: {
      step1: 'lighting the candle…',
      step2: 'hanging papel picado…',
      step3: 'preparing the offering…',
      ready: 'welcome',
    },
    hero: {
      greeting: '// hi, I am',
      name: 'Damian Tapia',
      role: 'full-stack developer · Mexico City',
      tagline: 'I build code',
      taglineHl: 'that outlives its author.',
      bio: 'Between life and bug. Two years raising code altars for startups and brands that want to be remembered.',
      cta1: 'view work()',
      cta2: 'contact.md',
      scroll: 'scroll · down',
    },
    about: {
      label: 'about me',
      title: 'Here lies the dev',
      subtitle: 'a brief offering',
      body: [
        'My name is Damian Tapia and I have been building web applications that people do not want to close for two years. I work with React, TypeScript and Node, but I move comfortably anywhere in the stack.',
        'I believe good software —like a good offering— is built with intention: every decision, every pixel, every function serves a purpose.',
        'When I am not coding, I am looking for a new way to brew myself a coffee.',
      ],
      meta: [
        { k: 'location', v: 'Mexico City, MX' },
        { k: 'experience', v: '2 years' },
        { k: 'status', v: '● available', live: true },
        { k: 'languages', v: 'ES native · EN B2' },
      ],
    },
    projects: {
      label: 'complete works',
      title: 'The proyect lotería',
      subtitle: 'four cards · four stories',
      featured: 'featured',
      viewAll: 'view all cards →',
      cards: [
        { num: '01', slug: 'proline', name: 'Proline', tag: 'Frontend Dev & UI/UX', year: '2025–now', stack: ['Next.js','TypeScript','SCSS/BEM','Storybook','Prisma'], blurb: 'Led 15+ wireframes and prototypes in Figma for 7+ critical modules. Built a library of 40+ reusable components under clean architecture, mobile-first and atomic design. Integrated Storybook, designed Prisma schemas, and implemented API endpoints.', icon: '🧱', featured: true, meta: '−18 hrs dev / sprint' },
        { num: '02', slug: 'xcamp', name: 'Xcamp', tag: 'Frontend Angular & UI/UX', year: '2025', stack: ['Angular 17','TypeScript','SCSS/BEM','Figma'], blurb: 'Optimized 30+ components and created ~15 new ones in Angular 17 aligned to the design system. Led responsive mobile and tablet migration for multi-step flows. Defined 8+ end-to-end flows in Figma.', icon: '🎯', meta: '−40% code duplication' },
        { num: '03', slug: 'clinica-pos', name: 'Clinical POS', tag: 'Fullstack freelance', year: '2023–2024', stack: ['MongoDB','Express','React','Node','JWT'], blurb: 'Fullstack app in production for a functional-medicine clinic: records, POS, inventory and partial-payment billing. CRUD for 200+ patients with roles, PDF reports and barcode scanning. POS with 50+ SKUs.', icon: '🏥', meta: 'ticket sync <100ms' },
        { num: '04', slug: 'co-labora', name: 'Co‑Labora', tag: 'Coworking platform', year: '2023–2024', stack: ['Next.js','TypeScript','Tailwind','MongoDB','AWS S3','Stripe'], blurb: 'Fullstack platform for discovering and renting coworking spaces, Figma to production. Google Maps, Stripe payments and SendGrid notifications. Image management with AWS S3 + Sharp.', icon: '🏢', meta: 'end-to-end shipped' },
      ],
    },
    stack: {
      label: 'toolbox',
      title: 'The technical altar',
      subtitle: 'seven candles lit',
      hint: 'hover · light the candle',
      cats: [
        { t: 'frontend', items: ['Angular 17+', 'React 18', 'Next.js 13+', 'TypeScript', 'JavaScript ES6+'] },
        { t: 'styling', items: ['Tailwind CSS', 'SCSS/SASS', 'DaisyUI', 'CSS-in-JS', 'BEM'] },
        { t: 'backend', items: ['Node.js', 'Express', 'PostgreSQL'] },
        { t: 'database', items: ['MongoDB', 'Prisma ORM'] },
        { t: 'tools', items: ['Git', 'Figma', 'Storybook', 'Jira', 'Postman', 'ClickUp', 'Asana', 'PostHog', 'GrowthBook'] },
        { t: 'ui/ux', items: ['Design Systems', 'Responsive Design', 'Mobile-First', 'Atomic Design', 'User Flow Optimization'] },
        { t: 'apis', items: ['REST APIs', 'Stripe API', 'Google Maps API'] },
      ],
    },
    contact: {
      label: 'offering',
      title: 'Let us leave an offering in your project.',
      subtitle: 'tell me what you want to build',
      emailBtn: 'copy email',
      copied: '✓ copied',
      or: 'or find me on',
      footer: 'made with ♥ and café de olla · may the bugs rest in peace · ',
    },
  },
};

